<?php

declare(strict_types=1);

// @generated by bin/generate-constants-stub.php
// phpcs:ignoreFile -- Arquivo auxiliar para autocompletar constantes no IDE.

if (!defined('ACC_MANAGER')) {
    define('ACC_MANAGER', 1);
}

if (!defined('ACC_TAG')) {
    define('ACC_TAG', 'Minha Conta');
}

if (!defined('ADMIN_DESC')) {
    define('ADMIN_DESC', 'Descrição do Painel de Controle');
}

if (!defined('ADMIN_MAINTENANCE')) {
    define('ADMIN_MAINTENANCE', 0);
}

if (!defined('ADMIN_MODE')) {
    define('ADMIN_MODE', 1);
}

if (!defined('ADMIN_NAME')) {
    define('ADMIN_NAME', 'Nome do CMS - Painel de Controle');
}

if (!defined('ADMIN_VERSION')) {
    define('ADMIN_VERSION', '3.5.0');
}

if (!defined('ADMIN_WC_CUSTOM')) {
    define('ADMIN_WC_CUSTOM', 1);
}

if (!defined('AGENCY_ADDR')) {
    define('AGENCY_ADDR', 'Rua Antonio Corsetti, 221 - Sala 1');
}

if (!defined('AGENCY_CITY')) {
    define('AGENCY_CITY', 'Caxias do Sul');
}

if (!defined('AGENCY_CONTACT')) {
    define('AGENCY_CONTACT', 'Marcos Moreira');
}

if (!defined('AGENCY_COUNTRY')) {
    define('AGENCY_COUNTRY', 'BRASIL');
}

if (!defined('AGENCY_EMAIL')) {
    define('AGENCY_EMAIL', 'marcos@zen.ppg.br');
}

if (!defined('AGENCY_NAME')) {
    define('AGENCY_NAME', 'Zen Agência Web');
}

if (!defined('AGENCY_PHONE')) {
    define('AGENCY_PHONE', '(54) 3419.9425');
}

if (!defined('AGENCY_SUPPORT')) {
    define('AGENCY_SUPPORT', '(54) 99634.9424');
}

if (!defined('AGENCY_UF')) {
    define('AGENCY_UF', 'RS');
}

if (!defined('AGENCY_URL')) {
    define('AGENCY_URL', 'https://zen.ppg.br');
}

if (!defined('AGENCY_ZIP')) {
    define('AGENCY_ZIP', '95084-220');
}

if (!defined('APP_ABOUTPAGE')) {
    define('APP_ABOUTPAGE', 0);
}

if (!defined('APP_ALBUMS')) {
    define('APP_ALBUMS', 0);
}

if (!defined('APP_CERTIFICATIONS')) {
    define('APP_CERTIFICATIONS', 0);
}

if (!defined('APP_COMMENTS')) {
    define('APP_COMMENTS', 1);
}

if (!defined('APP_CURIOSITIES')) {
    define('APP_CURIOSITIES', 0);
}

if (!defined('APP_CV')) {
    define('APP_CV', 0);
}

if (!defined('APP_DEBUG')) {
    define('APP_DEBUG', true);
}

if (!defined('APP_DEPOSITIONS')) {
    define('APP_DEPOSITIONS', 0);
}

if (!defined('APP_DOMAIN')) {
    define('APP_DOMAIN', 'https://besmarteletro.com');
}

if (!defined('APP_ENV')) {
    define('APP_ENV', 'local');
}

if (!defined('APP_HELLO')) {
    define('APP_HELLO', 0);
}

if (!defined('APP_HOMEPAGE')) {
    define('APP_HOMEPAGE', 0);
}

if (!defined('APP_LANDING_PAGES')) {
    define('APP_LANDING_PAGES', 0);
}

if (!defined('APP_LEADS')) {
    define('APP_LEADS', 0);
}

if (!defined('APP_LINKTREE')) {
    define('APP_LINKTREE', 0);
}

if (!defined('APP_LINK_PAGES')) {
    define('APP_LINK_PAGES', 1);
}

if (!defined('APP_LINK_POSTS')) {
    define('APP_LINK_POSTS', 1);
}

if (!defined('APP_LINK_PRODUCTS')) {
    define('APP_LINK_PRODUCTS', 1);
}

if (!defined('APP_LINK_PROPERTIES')) {
    define('APP_LINK_PROPERTIES', 1);
}

if (!defined('APP_LOCALE')) {
    define('APP_LOCALE', 'pt_BR');
}

if (!defined('APP_LOCALHOST')) {
    define('APP_LOCALHOST', 'https://localhost/besmarteletro.com');
}

if (!defined('APP_MATERIALS')) {
    define('APP_MATERIALS', 0);
}

if (!defined('APP_NAME')) {
    define('APP_NAME', 'BE.SMART');
}

if (!defined('APP_OUVIDORIA')) {
    define('APP_OUVIDORIA', 0);
}

if (!defined('APP_PAGES')) {
    define('APP_PAGES', 1);
}

if (!defined('APP_PARTNERS')) {
    define('APP_PARTNERS', 0);
}

if (!defined('APP_PDT')) {
    define('APP_PDT', 1);
}

if (!defined('APP_POSTS')) {
    define('APP_POSTS', 1);
}

if (!defined('APP_POSTS_AMP')) {
    define('APP_POSTS_AMP', 0);
}

if (!defined('APP_POSTS_INSTANT_ARTICLE')) {
    define('APP_POSTS_INSTANT_ARTICLE', 0);
}

if (!defined('APP_PROJETOS')) {
    define('APP_PROJETOS', 0);
}

if (!defined('APP_REPRESENTATIVES')) {
    define('APP_REPRESENTATIVES', 0);
}

if (!defined('APP_SEARCH')) {
    define('APP_SEARCH', 1);
}

if (!defined('APP_SEGMENTS')) {
    define('APP_SEGMENTS', 0);
}

if (!defined('APP_SERVICES')) {
    define('APP_SERVICES', 0);
}

if (!defined('APP_SKILLSPAGE')) {
    define('APP_SKILLSPAGE', 0);
}

if (!defined('APP_SLIDE')) {
    define('APP_SLIDE', 1);
}

if (!defined('APP_THANKYOU_PAGES')) {
    define('APP_THANKYOU_PAGES', 0);
}

if (!defined('APP_THEME')) {
    define('APP_THEME', 'besmart');
}

if (!defined('APP_TIMEZONE')) {
    define('APP_TIMEZONE', 'America/Sao_Paulo');
}

if (!defined('APP_USERS')) {
    define('APP_USERS', 1);
}

if (!defined('APP_VIDEOS')) {
    define('APP_VIDEOS', 0);
}

if (!defined('AVATAR_H')) {
    define('AVATAR_H', 500);
}

if (!defined('AVATAR_W')) {
    define('AVATAR_W', 500);
}

if (!defined('BASE')) {
    define('BASE', 'https://besmarteletro.com');
}

if (!defined('COMMENT_MODERATE')) {
    define('COMMENT_MODERATE', 1);
}

if (!defined('COMMENT_ON_PAGES')) {
    define('COMMENT_ON_PAGES', 0);
}

if (!defined('COMMENT_ON_POSTS')) {
    define('COMMENT_ON_POSTS', 1);
}

if (!defined('COMMENT_ON_PRODUCTS')) {
    define('COMMENT_ON_PRODUCTS', 0);
}

if (!defined('COMMENT_ORDER')) {
    define('COMMENT_ORDER', 'DESC');
}

if (!defined('COMMENT_RESPONSE_ORDER')) {
    define('COMMENT_RESPONSE_ORDER', 'ASC');
}

if (!defined('COMMENT_SEND_EMAIL')) {
    define('COMMENT_SEND_EMAIL', 1);
}

if (!defined('DB_ABOUTPAGE')) {
    define('DB_ABOUTPAGE', 'ws_about');
}

if (!defined('DB_ALBUMS')) {
    define('DB_ALBUMS', 'ws_albums');
}

if (!defined('DB_ALBUMS_IMAGE')) {
    define('DB_ALBUMS_IMAGE', 'ws_albums_images');
}

if (!defined('DB_AUTO_PING')) {
    define('DB_AUTO_PING', 1);
}

if (!defined('DB_AUTO_TRASH')) {
    define('DB_AUTO_TRASH', 1);
}

if (!defined('DB_BANNERS')) {
    define('DB_BANNERS', 'ws_banners');
}

if (!defined('DB_CARD_USER')) {
    define('DB_CARD_USER', 'trv_card_user');
}

if (!defined('DB_CATEGORIES')) {
    define('DB_CATEGORIES', 'ws_categories');
}

if (!defined('DB_CATEGORIES_PORTIFOLIO')) {
    define('DB_CATEGORIES_PORTIFOLIO', 'ws_categories_portifolio');
}

if (!defined('DB_CERT')) {
    define('DB_CERT', 'ws_certifications');
}

if (!defined('DB_CERT_IMAGE')) {
    define('DB_CERT_IMAGE', 'ws_certifications_images');
}

if (!defined('DB_CITIES')) {
    define('DB_CITIES', 'cities');
}

if (!defined('DB_COMMENTS')) {
    define('DB_COMMENTS', 'ws_comments');
}

if (!defined('DB_COMMENTS_LIKES')) {
    define('DB_COMMENTS_LIKES', 'ws_comments_likes');
}

if (!defined('DB_CONF')) {
    define('DB_CONF', 'ws_config');
}

if (!defined('DB_CURIOSITIES')) {
    define('DB_CURIOSITIES', 'ws_curiosities');
}

if (!defined('DB_CV')) {
    define('DB_CV', 'ws_job_candidates');
}

if (!defined('DB_DEPOSITIONS')) {
    define('DB_DEPOSITIONS', 'ws_depositions');
}

if (!defined('DB_HELLO')) {
    define('DB_HELLO', 'ws_hellobar');
}

if (!defined('DB_HOMEPAGE')) {
    define('DB_HOMEPAGE', 'ws_home');
}

if (!defined('DB_LANDING_PAGES')) {
    define('DB_LANDING_PAGES', 'ws_landingpages');
}

if (!defined('DB_LANDING_PAGES_IMAGES')) {
    define('DB_LANDING_PAGES_IMAGES', 'ws_landingpages_images');
}

if (!defined('DB_LEADS')) {
    define('DB_LEADS', 'ws_leads');
}

if (!defined('DB_MATCATEGORIES')) {
    define('DB_MATCATEGORIES', 'ws_matcategories');
}

if (!defined('DB_MATERIAIS')) {
    define('DB_MATERIAIS', 'ws_materiais');
}

if (!defined('DB_OUVIDORIA')) {
    define('DB_OUVIDORIA', 'ws_ouvidoria');
}

if (!defined('DB_PAGES')) {
    define('DB_PAGES', 'ws_pages');
}

if (!defined('DB_PAGES_IMAGE')) {
    define('DB_PAGES_IMAGE', 'ws_pages_images');
}

if (!defined('DB_PARTNERS')) {
    define('DB_PARTNERS', 'ws_partners');
}

if (!defined('DB_PDT')) {
    define('DB_PDT', 'ws_products');
}

if (!defined('DB_PDT_ATTR_COLORS')) {
    define('DB_PDT_ATTR_COLORS', 'ws_products_attributes_colors');
}

if (!defined('DB_PDT_ATTR_PRINTS')) {
    define('DB_PDT_ATTR_PRINTS', 'ws_products_attributes_prints');
}

if (!defined('DB_PDT_ATTR_SIZES')) {
    define('DB_PDT_ATTR_SIZES', 'ws_products_attributes_sizes');
}

if (!defined('DB_PDT_BRANDS')) {
    define('DB_PDT_BRANDS', 'ws_products_brands');
}

if (!defined('DB_PDT_CATS')) {
    define('DB_PDT_CATS', 'ws_products_categories');
}

if (!defined('DB_PDT_CATS_TRAVI')) {
    define('DB_PDT_CATS_TRAVI', 'ws_products_categories_travi');
}

if (!defined('DB_PDT_COMBO')) {
    define('DB_PDT_COMBO', 'ws_products_combo');
}

if (!defined('DB_PDT_COUPONS')) {
    define('DB_PDT_COUPONS', 'ws_products_coupons');
}

if (!defined('DB_PDT_FORMAT_TRAVI')) {
    define('DB_PDT_FORMAT_TRAVI', 'ws_products_formats_travi');
}

if (!defined('DB_PDT_GALLERY')) {
    define('DB_PDT_GALLERY', 'ws_products_gallery');
}

if (!defined('DB_PDT_GALLERY_TRAVI')) {
    define('DB_PDT_GALLERY_TRAVI', 'ws_products_gallery_travi');
}

if (!defined('DB_PDT_GROUPS_ATTR')) {
    define('DB_PDT_GROUPS_ATTR', 'ws_products_groups_attributes');
}

if (!defined('DB_PDT_IMAGE')) {
    define('DB_PDT_IMAGE', 'ws_products_images');
}

if (!defined('DB_PDT_IMAGE_CAT_TRAVI')) {
    define('DB_PDT_IMAGE_CAT_TRAVI', 'ws_products_images_cat_travi');
}

if (!defined('DB_PDT_IMAGE_TRAVI')) {
    define('DB_PDT_IMAGE_TRAVI', 'ws_products_images_travi');
}

if (!defined('DB_PDT_LINES')) {
    define('DB_PDT_LINES', 'ws_products_lines');
}

if (!defined('DB_PDT_PROCESS_TRAVI')) {
    define('DB_PDT_PROCESS_TRAVI', 'ws_products_processes_travi');
}

if (!defined('DB_PDT_STOCK')) {
    define('DB_PDT_STOCK', 'ws_products_stock');
}

if (!defined('DB_PDT_TRAVI')) {
    define('DB_PDT_TRAVI', 'ws_products_travi');
}

if (!defined('DB_PDT_WISHLIST')) {
    define('DB_PDT_WISHLIST', 'ws_products_wishlist');
}

if (!defined('DB_PORTIFOLIO')) {
    define('DB_PORTIFOLIO', 'ws_portifolio');
}

if (!defined('DB_PORTIFOLIO_IMAGES')) {
    define('DB_PORTIFOLIO_IMAGES', 'ws_portifolio_images');
}

if (!defined('DB_POSTS')) {
    define('DB_POSTS', 'ws_posts');
}

if (!defined('DB_POSTS_IMAGE')) {
    define('DB_POSTS_IMAGE', 'ws_posts_images');
}

if (!defined('DB_REPRESENTATIVES')) {
    define('DB_REPRESENTATIVES', 'ws_representatives');
}

if (!defined('DB_SEARCH')) {
    define('DB_SEARCH', 'ws_search');
}

if (!defined('DB_SEG')) {
    define('DB_SEG', 'ws_segments');
}

if (!defined('DB_SEG_GALLERY')) {
    define('DB_SEG_GALLERY', 'ws_segments_gallery');
}

if (!defined('DB_SEG_IMAGE')) {
    define('DB_SEG_IMAGE', 'ws_segments_images');
}

if (!defined('DB_SKILLSPAGE')) {
    define('DB_SKILLSPAGE', 'ws_skills');
}

if (!defined('DB_SLIDES')) {
    define('DB_SLIDES', 'ws_slides');
}

if (!defined('DB_STATES')) {
    define('DB_STATES', 'states');
}

if (!defined('DB_SVC')) {
    define('DB_SVC', 'ws_services');
}

if (!defined('DB_SVC_GALLERY')) {
    define('DB_SVC_GALLERY', 'ws_services_gallery');
}

if (!defined('DB_SVC_IMAGE')) {
    define('DB_SVC_IMAGE', 'ws_services_images');
}

if (!defined('DB_TEMPLATE_COLORS')) {
    define('DB_TEMPLATE_COLORS', 'ws_template_colors');
}

if (!defined('DB_THANKYOU_PAGES')) {
    define('DB_THANKYOU_PAGES', 'ws_thankyoupages');
}

if (!defined('DB_USERS')) {
    define('DB_USERS', 'ws_users');
}

if (!defined('DB_USERS_ADDR')) {
    define('DB_USERS_ADDR', 'ws_users_address');
}

if (!defined('DB_USERS_NOTES')) {
    define('DB_USERS_NOTES', 'ws_users_notes');
}

if (!defined('DB_VIEWS_ONLINE')) {
    define('DB_VIEWS_ONLINE', 'ws_siteviews_online');
}

if (!defined('DB_VIEWS_VIEWS')) {
    define('DB_VIEWS_VIEWS', 'ws_siteviews_views');
}

if (!defined('DB_WC_API')) {
    define('DB_WC_API', 'workcontrol_api');
}

if (!defined('DB_WC_CODE')) {
    define('DB_WC_CODE', 'workcontrol_code');
}

if (!defined('DB_YOUTUBE')) {
    define('DB_YOUTUBE', 'ws_youtube');
}

if (!defined('GOOGLE_MAPS_API_KEY')) {
    define('GOOGLE_MAPS_API_KEY', 'sua_chave_google_maps');
}

if (!defined('IMAGE_H')) {
    define('IMAGE_H', 628);
}

if (!defined('IMAGE_W')) {
    define('IMAGE_W', 1200);
}

if (!defined('INCLUDE_PATH')) {
    define('INCLUDE_PATH', 'https://besmarteletro.com/themes/besmart');
}

if (!defined('LEVEL_WC_ABOUTPAGE')) {
    define('LEVEL_WC_ABOUTPAGE', 6);
}

if (!defined('LEVEL_WC_ALBUMS')) {
    define('LEVEL_WC_ALBUMS', 9);
}

if (!defined('LEVEL_WC_CERTIFICATIONS')) {
    define('LEVEL_WC_CERTIFICATIONS', 9);
}

if (!defined('LEVEL_WC_COMMENTS')) {
    define('LEVEL_WC_COMMENTS', 6);
}

if (!defined('LEVEL_WC_CONFIG_API')) {
    define('LEVEL_WC_CONFIG_API', 10);
}

if (!defined('LEVEL_WC_CONFIG_CODES')) {
    define('LEVEL_WC_CONFIG_CODES', 10);
}

if (!defined('LEVEL_WC_CONFIG_MASTER')) {
    define('LEVEL_WC_CONFIG_MASTER', 10);
}

if (!defined('LEVEL_WC_CURIOSITIES')) {
    define('LEVEL_WC_CURIOSITIES', 9);
}

if (!defined('LEVEL_WC_CV')) {
    define('LEVEL_WC_CV', 9);
}

if (!defined('LEVEL_WC_DEPOSITIONS')) {
    define('LEVEL_WC_DEPOSITIONS', 9);
}

if (!defined('LEVEL_WC_HELLO')) {
    define('LEVEL_WC_HELLO', 9);
}

if (!defined('LEVEL_WC_HOMEPAGE')) {
    define('LEVEL_WC_HOMEPAGE', 6);
}

if (!defined('LEVEL_WC_LANDING_PAGES')) {
    define('LEVEL_WC_LANDING_PAGES', 9);
}

if (!defined('LEVEL_WC_LEADS')) {
    define('LEVEL_WC_LEADS', 9);
}

if (!defined('LEVEL_WC_LINKTREE')) {
    define('LEVEL_WC_LINKTREE', 6);
}

if (!defined('LEVEL_WC_OUVIDORIA')) {
    define('LEVEL_WC_OUVIDORIA', 9);
}

if (!defined('LEVEL_WC_PAGES')) {
    define('LEVEL_WC_PAGES', 9);
}

if (!defined('LEVEL_WC_PARTNERS')) {
    define('LEVEL_WC_PARTNERS', 9);
}

if (!defined('LEVEL_WC_POSTS')) {
    define('LEVEL_WC_POSTS', 6);
}

if (!defined('LEVEL_WC_PRODUCTS')) {
    define('LEVEL_WC_PRODUCTS', 9);
}

if (!defined('LEVEL_WC_PROJETOS')) {
    define('LEVEL_WC_PROJETOS', 6);
}

if (!defined('LEVEL_WC_REPORTS')) {
    define('LEVEL_WC_REPORTS', 9);
}

if (!defined('LEVEL_WC_REPRESENTATIVES')) {
    define('LEVEL_WC_REPRESENTATIVES', 9);
}

if (!defined('LEVEL_WC_SEGMENTS')) {
    define('LEVEL_WC_SEGMENTS', 9);
}

if (!defined('LEVEL_WC_SERVICES')) {
    define('LEVEL_WC_SERVICES', 9);
}

if (!defined('LEVEL_WC_SKILLSPAGE')) {
    define('LEVEL_WC_SKILLSPAGE', 6);
}

if (!defined('LEVEL_WC_SLIDES')) {
    define('LEVEL_WC_SLIDES', 9);
}

if (!defined('LEVEL_WC_THANKYOU_PAGES')) {
    define('LEVEL_WC_THANKYOU_PAGES', 9);
}

if (!defined('LEVEL_WC_USERS')) {
    define('LEVEL_WC_USERS', 9);
}

if (!defined('LEVEL_WC_VIDEOS')) {
    define('LEVEL_WC_VIDEOS', 9);
}

if (!defined('MAIL_HOST')) {
    define('MAIL_HOST', 'mail.besmarteletro.com');
}

if (!defined('MAIL_MODE')) {
    define('MAIL_MODE', 'tls');
}

if (!defined('MAIL_PASS')) {
    define('MAIL_PASS', '@Be01sm01');
}

if (!defined('MAIL_PORT')) {
    define('MAIL_PORT', '465');
}

if (!defined('MAIL_SENDER')) {
    define('MAIL_SENDER', 'BE.SMART');
}

if (!defined('MAIL_SMTP')) {
    define('MAIL_SMTP', 'sac@besmarteletro.com');
}

if (!defined('MAIL_TESTER')) {
    define('MAIL_TESTER', 'marcosleaomoreira@gmail.com');
}

if (!defined('MAIL_USER')) {
    define('MAIL_USER', 'sac@besmarteletro.com');
}

if (!defined('MERCADOPAGO_ACCESS_TOKEN')) {
    define('MERCADOPAGO_ACCESS_TOKEN', 'seu_token_acesso');
}

if (!defined('MERCADOPAGO_PUBLIC_KEY')) {
    define('MERCADOPAGO_PUBLIC_KEY', 'sua_chave_publica');
}

if (!defined('PAGSEGURO_EMAIL')) {
    define('PAGSEGURO_EMAIL', 'seu_email');
}

if (!defined('PAGSEGURO_TOKEN')) {
    define('PAGSEGURO_TOKEN', 'seu_token');
}

if (!defined('PAYPAL_CLIENT_ID')) {
    define('PAYPAL_CLIENT_ID', 'seu_client_id');
}

if (!defined('PAYPAL_SECRET')) {
    define('PAYPAL_SECRET', 'seu_secret');
}

if (!defined('RECAPTCHA_SECRET_KEY')) {
    define('RECAPTCHA_SECRET_KEY', 'seu_secret_recaptcha');
}

if (!defined('RECAPTCHA_SITE_KEY')) {
    define('RECAPTCHA_SITE_KEY', 'sua_chave_recaptcha');
}

if (!defined('REQUIRE_PATH')) {
    define('REQUIRE_PATH', 'themes/besmart');
}

if (!defined('SAC_URL')) {
    define('SAC_URL', 'https://seu-dominio.com.br');
}

if (!defined('SEGMENT_FB_PAGE_ID')) {
    define('SEGMENT_FB_PAGE_ID', '');
}

if (!defined('SEGMENT_FB_PIXEL_ID')) {
    define('SEGMENT_FB_PIXEL_ID', '');
}

if (!defined('SEGMENT_GL_ADWORDS_ID')) {
    define('SEGMENT_GL_ADWORDS_ID', '');
}

if (!defined('SEGMENT_GL_ADWORDS_LABEL')) {
    define('SEGMENT_GL_ADWORDS_LABEL', '');
}

if (!defined('SEGMENT_GL_ANALYTICS')) {
    define('SEGMENT_GL_ANALYTICS', '');
}

if (!defined('SEGMENT_GL_TAGMANAGER')) {
    define('SEGMENT_GL_TAGMANAGER', 'GTM-MBQ2G8X');
}

if (!defined('SEGMENT_WC_BLOG')) {
    define('SEGMENT_WC_BLOG', 1);
}

if (!defined('SEGMENT_WC_USER')) {
    define('SEGMENT_WC_USER', 1);
}

if (!defined('SIS_CACHE_TIME')) {
    define('SIS_CACHE_TIME', 10);
}

if (!defined('SIS_CONFIG_WC')) {
    define('SIS_CONFIG_WC', 1);
}

if (!defined('SIS_DB_HOST')) {
    define('SIS_DB_HOST', 'localhost');
}

if (!defined('SIS_DB_NAME')) {
    define('SIS_DB_NAME', 'besmarteletro33_db');
}

if (!defined('SIS_DB_PASS')) {
    define('SIS_DB_PASS', '*TztifAJW#Z8');
}

if (!defined('SIS_DB_USER')) {
    define('SIS_DB_USER', 'besmarteletro33_root');
}

if (!defined('SITE_ADDR_ADDR')) {
    define('SITE_ADDR_ADDR', 'Av. Julio Vanzin, 1600 - Área Industrial');
}

if (!defined('SITE_ADDR_CITY')) {
    define('SITE_ADDR_CITY', 'Lagoa Vermelha');
}

if (!defined('SITE_ADDR_CNPJ')) {
    define('SITE_ADDR_CNPJ', '');
}

if (!defined('SITE_ADDR_COUNTRY')) {
    define('SITE_ADDR_COUNTRY', 'Brasil');
}

if (!defined('SITE_ADDR_DISTRICT')) {
    define('SITE_ADDR_DISTRICT', 'Área Industrial');
}

if (!defined('SITE_ADDR_EMAIL')) {
    define('SITE_ADDR_EMAIL', 'vendas@besmarteletro.com');
}

if (!defined('SITE_ADDR_IE')) {
    define('SITE_ADDR_IE', '');
}

if (!defined('SITE_ADDR_NAME')) {
    define('SITE_ADDR_NAME', 'BE.SMART');
}

if (!defined('SITE_ADDR_PHONE_A')) {
    define('SITE_ADDR_PHONE_A', '(54) 3358-6530');
}

if (!defined('SITE_ADDR_RS')) {
    define('SITE_ADDR_RS', 'Be Smart Eletro');
}

if (!defined('SITE_ADDR_SAC')) {
    define('SITE_ADDR_SAC', '0800 999 2000');
}

if (!defined('SITE_ADDR_SITE')) {
    define('SITE_ADDR_SITE', 'besmarteletro.com');
}

if (!defined('SITE_ADDR_UF')) {
    define('SITE_ADDR_UF', 'RS');
}

if (!defined('SITE_ADDR_WHATS')) {
    define('SITE_ADDR_WHATS', '(54) 99662-1197');
}

if (!defined('SITE_ADDR_WHATS_TRIM')) {
    define('SITE_ADDR_WHATS_TRIM', '55(54)99662-1197');
}

if (!defined('SITE_ADDR_ZIP')) {
    define('SITE_ADDR_ZIP', '93300-000');
}

if (!defined('SITE_DESC')) {
    define('SITE_DESC', 'Bem-vindo à BE.SMART, o seu destino para uma vida inteligente e conectada em sua casa. Nós somos mais do que uma loja de eletrodomésticos; somos seus parceiros na busca por praticidade, eficiência e inovação para tornar o seu lar mais inteligente.');
}

if (!defined('SITE_FONT_NAME')) {
    define('SITE_FONT_NAME', 'Barlow+Semi+Condensed');
}

if (!defined('SITE_FONT_WEIGHT')) {
    define('SITE_FONT_WEIGHT', '300;400;600;700');
}

if (!defined('SITE_NAME')) {
    define('SITE_NAME', 'BE.SMART');
}

if (!defined('SITE_SOCIAL_FB')) {
    define('SITE_SOCIAL_FB', 1);
}

if (!defined('SITE_SOCIAL_FB_APP')) {
    define('SITE_SOCIAL_FB_APP', '');
}

if (!defined('SITE_SOCIAL_FB_AUTHOR')) {
    define('SITE_SOCIAL_FB_AUTHOR', 'MundoBeSmart');
}

if (!defined('SITE_SOCIAL_FB_PAGE')) {
    define('SITE_SOCIAL_FB_PAGE', 'MundoBeSmart');
}

if (!defined('SITE_SOCIAL_FB_PAGE_ID')) {
    define('SITE_SOCIAL_FB_PAGE_ID', '');
}

if (!defined('SITE_SOCIAL_INSTAGRAM')) {
    define('SITE_SOCIAL_INSTAGRAM', 'mundobesmart');
}

if (!defined('SITE_SOCIAL_LINKEDIN')) {
    define('SITE_SOCIAL_LINKEDIN', '');
}

if (!defined('SITE_SOCIAL_NAME')) {
    define('SITE_SOCIAL_NAME', 'BE.SMART');
}

if (!defined('SITE_SOCIAL_TWITTER')) {
    define('SITE_SOCIAL_TWITTER', '');
}

if (!defined('SITE_SOCIAL_YOUTUBE')) {
    define('SITE_SOCIAL_YOUTUBE', '');
}

if (!defined('SITE_SUBNAME')) {
    define('SITE_SUBNAME', 'Eletro');
}

if (!defined('SLIDE_H')) {
    define('SLIDE_H', 900);
}

if (!defined('SLIDE_W')) {
    define('SLIDE_W', 1920);
}

if (!defined('STORAGE_DRIVER')) {
    define('STORAGE_DRIVER', 'local');
}

if (!defined('STORAGE_PATH')) {
    define('STORAGE_PATH', '/uploads');
}

if (!defined('THEME')) {
    define('THEME', 'besmart');
}

if (!defined('THUMB_H')) {
    define('THUMB_H', 800);
}

if (!defined('THUMB_W')) {
    define('THUMB_W', 800);
}

if (!defined('VIDEO_H')) {
    define('VIDEO_H', 720);
}

if (!defined('VIDEO_W')) {
    define('VIDEO_W', 1280);
}
